# Generated by Django 4.0.2 on 2022-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.IntegerField()),
                ('profile_image', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
