# Generated by Django 4.0.2 on 2022-02-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrest', '0002_employee_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
